# Generated by Django 4.2.30 on 2026-06-09 00:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='title')),
                ('slug', models.SlugField(max_length=320, unique=True)),
                ('standfirst', models.TextField(help_text='One-paragraph summary shown under the title and in the writing list.', verbose_name='standfirst')),
                ('assumes', models.CharField(blank=True, help_text='Prerequisite knowledge shown in the article sidebar.', max_length=200, verbose_name='assumes')),
                ('body_md', models.TextField(help_text='Write in Markdown. Fenced code blocks (```python), tables, and raw HTML blocks (e.g. <div class="art-note">) are all supported.', verbose_name='body (Markdown)')),
                ('body_html', models.TextField(blank=True, editable=False, verbose_name='body (HTML)')),
                ('word_count', models.PositiveIntegerField(default=0, editable=False)),
                ('read_time', models.PositiveIntegerField(default=0, editable=False, help_text='Estimated reading time in minutes (auto-calculated).')),
                ('published_at', models.DateField(verbose_name='published date')),
                ('is_published', models.BooleanField(default=False, verbose_name='published')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_url', models.URLField(blank=True, help_text='Original URL if this article was imported from an external platform.', verbose_name='source URL')),
                ('imported_from', models.CharField(blank=True, help_text='Platform name: "medium", "hashnode", etc. Empty for original content.', max_length=50, verbose_name='imported from')),
                ('also_read', models.ForeignKey(blank=True, help_text='Another article linked in the sidebar.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referenced_by', to='writing.article', verbose_name='also read')),
            ],
            options={
                'verbose_name': 'article',
                'verbose_name_plural': 'articles',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('filter_key', models.CharField(max_length=30, verbose_name='filter key')),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'series',
                'verbose_name_plural': 'series',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CaseStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(help_text='Display number: 1 → 001, 2 → 002 …', verbose_name='number')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('slug', models.SlugField(unique=True)),
                ('category', models.CharField(max_length=100, verbose_name='category')),
                ('subcategory', models.CharField(blank=True, max_length=100, verbose_name='subcategory')),
                ('subtitle', models.TextField(verbose_name='subtitle')),
                ('short_desc', models.TextField(verbose_name='short description')),
                ('role', models.CharField(max_length=200, verbose_name='role')),
                ('stack', models.CharField(max_length=200, verbose_name='stack')),
                ('integrations', models.CharField(blank=True, max_length=200, verbose_name='integrations')),
                ('status', models.CharField(max_length=100, verbose_name='status')),
                ('tech_tags', models.JSONField(default=list, help_text='JSON list of tag strings, e.g. ["Django", "DRF", "PostgreSQL"].', verbose_name='tech tags')),
                ('is_dark_card', models.BooleanField(default=False, help_text='Dark background on the homepage work-grid card (used for SwapFada).', verbose_name='dark card')),
                ('is_wide_card', models.BooleanField(default=False, help_text='Full-width card spanning both columns (used for Ajo).', verbose_name='wide card')),
                ('body_md', models.TextField(verbose_name='body (Markdown)')),
                ('body_html', models.TextField(blank=True, editable=False, verbose_name='body (HTML)')),
                ('is_published', models.BooleanField(default=True, verbose_name='published')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('next_case_study', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous', to='writing.casestudy', verbose_name='next case study')),
                ('related_article', models.ForeignKey(blank=True, help_text='Article linked in the "Read the article" section at the bottom.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='writing.article', verbose_name='related article')),
            ],
            options={
                'verbose_name': 'case study',
                'verbose_name_plural': 'case studies',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='article',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='writing.series', verbose_name='series'),
        ),
    ]
