# Generated by Django 4.2.30 on 2026-06-09 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OpenSourceProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('description', models.TextField(verbose_name='description')),
                ('status', models.CharField(choices=[('building', 'Building'), ('planned', 'In progress'), ('live', 'Live'), ('archived', 'Archived')], max_length=20, verbose_name='status')),
                ('tags', models.JSONField(default=list, help_text='List of tag strings, e.g. ["Python", "Django", "CLI"].', verbose_name='tags')),
                ('github_url', models.URLField(blank=True, verbose_name='GitHub URL')),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'open source project',
                'verbose_name_plural': 'open source projects',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_description', models.TextField(default='I build financial infrastructure and developer tooling.', verbose_name='hero description')),
                ('skills_chips', models.JSONField(default=list, help_text='List of skill chip labels shown in the hero, e.g. ["Django · DRF", "Python"].', verbose_name='skills chips')),
                ('available_for_work', models.BooleanField(default=True, verbose_name='available for work')),
                ('contact_email', models.EmailField(default='sherif@sifusherif.dev', max_length=254, verbose_name='contact email')),
                ('about_html', models.TextField(blank=True, help_text='HTML for the About section. Use <p> tags. <strong> renders in full ink colour.', verbose_name='about text (HTML)')),
                ('github_url', models.URLField(blank=True, verbose_name='GitHub URL')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='LinkedIn URL')),
                ('medium_url', models.URLField(blank=True, default='https://medium.com/@sifusherif', verbose_name='Medium URL')),
                ('footer_tagline', models.CharField(default='Abdulazeez Sherif — Abuja, Nigeria', max_length=200, verbose_name='footer tagline')),
                ('established_year', models.PositiveSmallIntegerField(default=2026, verbose_name='established year')),
            ],
            options={
                'verbose_name': 'site settings',
                'verbose_name_plural': 'site settings',
            },
        ),
    ]
